# Generated by Django 4.2.11 on 2024-04-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=50)),
                ('shopping_cycle', models.IntegerField(choices=[(0, '毎月'), (1, '隔週'), (2, '毎週')], default=0)),
                ('shopping_day', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], null=True)),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')], null=True)),
            ],
            options={
                'db_table': 'lists',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('line_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user_icon', models.CharField(blank=True, max_length=100, null=True)),
                ('invitation', models.BooleanField(default=False)),
                ('request', models.BooleanField(default=False)),
                ('have_list', models.BooleanField(default=False)),
                ('default_list', models.BooleanField(default=True)),
                ('remind', models.BooleanField(default=True)),
                ('remind_timing', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('remind_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('authority', models.BooleanField(default=False)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.user')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.list')),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.AddField(
            model_name='list',
            name='owner_id',
            field=models.ForeignKey(db_column='owner_id', on_delete=django.db.models.deletion.CASCADE, to='shop.user'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('color', models.IntegerField(blank=True, choices=[(0, '赤'), (1, '青'), (2, '緑')], null=True)),
                ('consume_cycle', models.IntegerField(default=30)),
                ('last_purchase_at', models.DateField(blank=True, null=True)),
                ('last_open_at', models.DateField(blank=True, null=True)),
                ('link', models.CharField(max_length=255)),
                ('to_list', models.BooleanField(default=False)),
                ('remind_by_item', models.BooleanField(default=True)),
                ('manage_target', models.BooleanField(default=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.list')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
