# Generated by Django 4.2.11 on 2024-04-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
