# Generated by Django 4.2.11 on 2024-05-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_invitee_member_invitee_id_remove_list_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='shared_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='shop.list'),
        ),
    ]
